### ISSUE TITLE
Question: Significance of yuv420p

### ISSUE THREAD

**Issue by vaage** [streamlinevideo/streamline#18]
In many of the ffmpeg commands `format=yuv420p` is used. What does this mean? Is it the input resolution? If so, why create 720p output from 420p input?

**Comment by e3z8** [comment]
Thats just ensuring that the color space is yuv4:2:0.  its not changing the resolution.

**Comment by colleenkhenry** [comment]
Yes that makes sure the video is 4.2.0 8 bit color.

**Comment by vaage** [comment]
Thanks @e3z8  and @colleenkhenry.
