### ISSUE TITLE
http.upload plugin is removed from caddy software 

### ISSUE THREAD

**Issue by prashanthag** [streamlinevideo/streamline#21]
http.upload plugin is removed from caddy software .. so what we need to install in place of it ?

curl https://getcaddy.com | bash -s personal hook.service,http.cors,http.upload
I just installed curl https://getcaddy.com | bash -s personal hook.service,http.cors
but it seems it might be a problem ?

**Comment by colleenkhenry** [comment]
We could easily replace it with nginx with the HTTP PUT method enabled or
even better I'll go ahead and add in the server from the low latency
project on this same repo :).

**Comment by prashanthag** [comment]
Hi,
Thanks for the reply.
I am novice to this server stuff .
If possible would you add nginx instruction?

**Comment by colleenkhenry** [comment]
Basically you want to allow the HTTP PUT method / WebDAV in NGINX. 

http://nginx.org/en/docs/http/ngx_http_dav_module.html

I'll update the full instructions though with a big fresh update. I'll try to find time today.

**Comment by prashanthag** [comment]
Found in caddy plugin   https://caddyserver.com/docs/http.webdav  worked perfectly fine 

- changes in caddyFile 

:80

root /home/ubuntu/streamline/www
webdav  {
    scope       /home/ubuntu/streamline/www
    modify      true
    allow       /home/ubuntu/streamline/www
}

- installation of  caddy : 

curl https://getcaddy.com | bash -s personal hook.service,http.cors,http.webdav

can you please make these changes in git  ?

**Comment by prashanthag** [comment]
sent you the pull requests

**Comment by colleenkhenry** [comment]
Oh sorry I just saw this. Great. 

Though, I think I'm going to eliminate the origin server completely and replace it with mediastore soon. I'll accept them for now, but, FYI I might go in that direction soon :).

**Comment by colleenkhenry** [comment]
Merged.
